# railway.toml
[project]
name = "backend"

# Service configuration for the backend
[[services]]
name = "backend"
path = "backend/"

# Set up the install, build, and start commands
[services.deploy]
installCommand = "pnpm install"
buildCommand = "pnpm run build"
startCommand = "pnpm run start:prod"